NUMBER_OF_REPETITIONS = range(1, 11)
for index in NUMBER_OF_REPETITIONS:
    print(f"Let's print out the multiply table for {index}")
    print(f"{index} x 0 = {index * 0}")
    print(f"{index} x 1 = {index * 1}")
    print(f"{index} x 2 = {index * 2}")
    print(f"{index} x 3 = {index * 3}")
    print(f"{index} x 4 = {index * 4}")
    print(f"{index} x 5 = {index * 5}")
    print(f"{index} x 6 = {index * 6}")
    print(f"{index} x 7 = {index * 7}")
    print(f"{index} x 8 = {index * 8}")
    print(f"{index} x 9 = {index * 9}")
    print(f"{index} x 10 = {index * 10}")
